name: Ruby on Rails & PostgreSQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '114.0.5735.90'
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: 3.0.1

    - name: Install dependencies
      run: bundle install

    - name: Set up PostgreSQL
      run: |
        sudo apt-get install postgresql libpq-dev
        sudo service postgresql start
        sudo -u postgres createuser --superuser "$USER"

    - name: Set up Database
      run: bundle exec rails db:migrate:reset
      env:
        RAILS_ENV: test

    - name: Run tests
      run: bundle exec rake
